In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x[0],x[1],x[2],x[3],x[4])
x[0]=6
print(x)

1 2 3 4 5
[6 2 3 4 5]


In [3]:
import numpy as np

# create an array from a list
npArray1 = np.array([1,2,3,4,5])

# create 2D array
npArray2 = np.array([[77,88,99],[66,77,32],[33,56,87]])

# create an array from a tuple
npArray3 = np.array((1,2,3,4,5))

# create an array from a range 
npArray4 = np.array(range(2,4))

print(npArray1)
print(npArray2)
print(npArray3)
print(npArray4)

[1 2 3 4 5]
[[77 88 99]
 [66 77 32]
 [33 56 87]]
[1 2 3 4 5]
[2 3]


In [5]:
import numpy as np
x = np.array([[1,2],[3,4]])

print(np.size(x))
print(np.shape(x))
print(np.ndim(x))

# same

print(x.size)
print(x.shape)
print(x.ndim)


4
(2, 2)
2
4
(2, 2)
2


In [8]:
import numpy as np
a = np.array([[1,2],[3,4]],dtype=float)
b = np.array([[5,6],[5,5]],dtype=float)
print(a*b)

[[ 5. 12.]
 [15. 20.]]


In [11]:
import numpy as np
a = np.array([2,4,4],dtype=float)
b = np.array([3,6,5],dtype=float)

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a/b)
print(a%b)
print(a**b)

[ 5. 10.  9.]
[-1. -2. -1.]
[ 6. 24. 20.]
[0. 0. 0.]
[0.66666667 0.66666667 0.8       ]
[2. 4. 4.]
[   8. 4096. 1024.]


In [12]:
# array 2D
a = np.array([[2,4],[5,2]],dtype=float)
b = np.array([[2,6],[6,3]],dtype=float)
print(a*b)

[[ 4. 24.]
 [30.  6.]]


In [15]:
# dot product 
a = np.array([[3,2,5],[2,9,4]])
b = np.array([[3,5],[34,56],[45,3]])
c = np.dot(b,a)
print(c)

[[ 19  51  35]
 [214 572 394]
 [141 117 237]]


In [16]:
a = np.array([2,6,2])
print(a.sum())
print(b.prod())

10
3855600


In [17]:
a = np.array([[1,2],[2,4],[4,1]])
b = np.array([1,2])
print(a+b)


[[2 4]
 [3 6]
 [5 3]]


In [18]:
a = np.array([9,42],dtype=float)
print(np.sqrt(a))

[3.        6.4807407]


In [20]:
a = np.array([1,2,3],dtype=float)
print(a.mean())
print(np.mean(a))

print(a.var())
print(np.var(a))

print(a.std())
print(np.std(a))

2.0
2.0
0.6666666666666666
0.6666666666666666
0.816496580927726
0.816496580927726


In [22]:
a = np.array([7,2,4,1,5,6,6])
b = sorted(a)
print(b)

[1, 2, 4, 5, 6, 6, 7]


In [24]:
a = np.array([5,2,5,7,1])
print(a.min())
print(np.min(a))

print(a.max())
print(np.max(a))

print(a.argmin())
print(np.argmin(a))

print(a.argmax())
print(np.argmax(a))

1
1
7
7
4
4
3
3


In [27]:
a = np.array([0,1,2,3,4,5,6])
print(a)

a[5] = 0
a[6] = 1

print(a)

[0 1 2 3 4 5 6]
[0 1 2 3 4 0 1]


In [34]:
new_array = np.array([[1,1,1],[1,1,1]])
print(new_array)
new_array[0,1] = 2
print("/n")
print(new_array)

[[1 1 1]
 [1 1 1]]
/n
[[1 2 1]
 [1 1 1]]


In [46]:
new_array = np.array([[1,1,1,],[1,1,1]])
print(new_array)

# row
new_array[0,:] = 2
# column
new_array[:,0] = 2
print("/n")
print(new_array)

[[1 1 1]
 [1 1 1]]
/n
[[2 2 2]
 [2 1 1]]


In [66]:
import numpy as np

array_a = np.array([0,1,2,3,4,5,6,7])
array_a[1:7:2]

array([1, 3, 5])

In [67]:
array_b = np.array([11,22,33,44,55])
array_b[0:1]

array([11])

In [68]:
array_c = np.array([0,1,2,3,4,5,6])
array_c[5:]

array([5, 6])

In [79]:
sampleArray = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,50]])
print(sampleArray)

print("/n")

# cut column
slice_array = sampleArray[::2,1:4:2]
print(slice_array)



[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 50]]
/n
[[ 6 12]
 [30 36]
 [54 50]]
